services:
  db:
    image: postgres:17.5
    container_name: trading-view-data
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - trading-view-data:/var/lib/postgresql/data
    networks:
      - trading-view-network
  
  tradingview-bot:
    build: .
    container_name: trading-view-bot
    env_file:
      - .env
    depends_on: 
      - db
    ports:
      - "80:80"
    networks:
      - trading-view-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - trading-view-network

networks:
  trading-view-network:

volumes:
  trading-view-data:
    external: true
    name: bot-test_trading-view-data